
[functions.crypto-balance]
enabled = true
verify_jwt = false
import_map = "./functions/crypto-balance/deno.json"
entrypoint = "./functions/crypto-balance/index.ts"

[functions.bank-connect]
enabled = true
verify_jwt = false
import_map = "./functions/bank-connect/deno.json"
entrypoint = "./functions/bank-connect/index.ts"
